version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: assignment_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: >
        echo 'db.runCommand("ping").ok' | 
        mongosh --username rootuser --password rootpass --authenticationDatabase admin --quiet --host localhost --port 27017 test
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://rootuser:rootpass@mongodb:27017/assignment_db?authSource=admin
      JWT_SECRET: 7650e9f60696ae0a9556b6195224ad71677d6a96f5a1a40ff40f28e946343360fee18719a32a96ad95adbc4f844363b0c710bb6562854b2bd45fd0b8c5289333
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo-data:
